USE BLPDB
GO

-- ADD BUSINESS VIEWS
CREATE VIEW [agency].SORTIE
AS
SELECT a.SORTIE_ID
	, a.SORTIE_NAME
	, a.SORTIE_POPULATION
	, a.COMPARTMENT_ID
FROM [agency]._SORTIE a
JOIN agency.USER_COMPARTMENT_CLASSIFICATION ucc ON
(
	(ucc.CLASSIFICATION_ID >= a.[CLASSIFICATION_ID] AND ucc.COMPARTMENT_ID = a.COMPARTMENT_ID )
	or 
	( a.COMPARTMENT_ID = 1 AND ucc.COMPARTMENT_ID = 1 AND ucc.CLASSIFICATION_ID >= a.[CLASSIFICATION_ID] )
)
JOIN agency.[USER] u ON
	u.USER_NAME = USER
	AND ucc.USER_ID = u.USER_ID
GO

GRANT SELECT ON [agency].SORTIE TO [BLRole];
GO

CREATE VIEW [agency].INFORMANT
AS
SELECT i.INFORMANT_ID
	,i.INFORMANT_FIRSTNAME
	,i.INFORMANT_LASTNAME
	,i.INFORMANT_GENDER
FROM [agency]._INFORMANT i
JOIN agency.USER_COMPARTMENT_CLASSIFICATION ucc ON
(
	(ucc.CLASSIFICATION_ID >= i.[CLASSIFICATION_ID] AND ucc.COMPARTMENT_ID = i.COMPARTMENT_ID )
	or 
	( i.COMPARTMENT_ID = 1 AND ucc.COMPARTMENT_ID = 1 AND ucc.CLASSIFICATION_ID >= i.[CLASSIFICATION_ID] )
)
JOIN agency.[USER] u ON
	u.USER_NAME = USER
	AND ucc.USER_ID = u.USER_ID
	
GO

GRANT SELECT ON [agency].INFORMANT TO [BLRole];
GO

CREATE VIEW [agency].[SECRET]
AS
SELECT 
	s.SECRET_ID
	,s.INFORMANT_ID
	,s.SORTIE_ID
	,s.SECRET_TITLE
	,s.SECRET_DESCRIPTION
	,s.SECRET_DATETIME
	,s.CLASSIFICATION_ID
	,s.COMPARTMENT_ID
	FROM [agency]._SECRET s
	JOIN agency.USER_COMPARTMENT_CLASSIFICATION ucc ON
	(
		(ucc.CLASSIFICATION_ID >= s.[CLASSIFICATION_ID] AND ucc.COMPARTMENT_ID = s.COMPARTMENT_ID )
		or 
		( s.COMPARTMENT_ID = 1 AND ucc.COMPARTMENT_ID = 1 AND ucc.CLASSIFICATION_ID >= s.[CLASSIFICATION_ID] )
	)
	JOIN agency.[USER] u ON
		u.USER_NAME = USER
		AND ucc.USER_ID = u.USER_ID
	
GO

GRANT SELECT ON [agency].[SECRET] TO [BLRole];
GO