USE BLPDB
GO

-- ADD BUSINESS AUDIT TABLES
CREATE TABLE [agency].[AUDIT](
	[AUDIT_TABLE_NAME] varchar(30) NOT NULL,
	[AUDIT_OPERATION] varchar(30) NOT NULL,
	[AUDIT_USER] varchar(50) NOT NULL,
	[AUDIT_TIME] [datetime] NOT NULL DEFAULT (GETDATE())
)